name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Building the project
    - name: Build project
      run: |
        mkdir build
        cmake -B build
        cmake --build build
      env:
        MAKEFLAGS: "-j2"

    # Running the tests
    - name: Run tests
      run: bin/instruction_tests